### ISSUE TITLE
Need simple way to change policy for the bucket to one of: [none, download, upload, public]

### ISSUE THREAD

**Issue by matthewdarwin** [rzrbld/adminio-ui#12]
In the video, it shows an edit screen for a bucket so as to set the lifecycle policy https://raw.githubusercontent.com/rzrbld/adminio-ui/master/images/image.gif

I built the current version on https://github.com/rzrbld/adminio-ui, but I don't seem to have this feature.

![image](https://user-images.githubusercontent.com/26171839/82259034-f0728500-9928-11ea-9fcd-7d94e8ffe998.png)

How to enable this edit bucket feature?

I can set the permissions from the command line, eg "mc policy set public test/new"

I'm new to this project, so sorry in advance if this is some basic question I missed in the documentation.

**Comment by matthewdarwin** [comment]
Or maybe the video is showing lifecycle policy tied to events?  Hard to tell.

My version has upload XML file for lifecycle editing which is awkward.  I only need to be able to change the lifecycle for the bucket itself to one of the 4 defined values: [none, download, upload, public]

**Comment by matthewdarwin** [comment]
Upgraded to 1.0 now.  I can see the edit quota feature.

**Comment by rzrbld** [comment]
Hi, yep, in "video" bucket edit has event edit form. if you'll enable bucket events (notifications) - yo must see this too. 

Bucket policies (none, download, upload, public and custom) - planned for the next update along with bucket tag support. By now you can do this in default minio web ui.

**Comment by matthewdarwin** [comment]
Great!  I look forward to a new release with this feature.
