### ISSUE TITLE
Use env vars from run-time.

### ISSUE THREAD

**Issue by redref** [rzrbld/adminio-ui#14]
Right now, the environment variables are gathered at build-time. It would be really usefull to be able to modify values at run-time. 

My usage : release-1.0 image in a k8s deployment.

Found https://www.jvandemo.com/how-to-use-environment-variables-to-configure-your-angular-application-without-a-rebuild/ as a possible solution.

Nevertheless, I want to thank for the great job on this app !

**Comment by rzrbld** [comment]
Hi, thanks. I'll try to implement this.
