### ISSUE TITLE
where can files be manually uploaded?

### ISSUE THREAD

**Issue by dberardo** [rzrbld/adminio-ui#25]
hello,

i have a correct setup of adminio API + UI and everything seems to work fine, but i am wondering if and how can i manually upload files in existing buckets from the GUI.

let me know if possible

**Comment by rzrbld** [comment]
@dberardo hi, you can upload files via default minio ui or [mc cli-utility](https://github.com/minio/mc) or [cyberduck](https://cyberduck.io/)

**Comment by dberardo** [comment]
oh i see, but then i have to expose a port of the minio server on the host. 

Well if this was a design choice i guess there i reason.

take care
